version: '3'

services:
  server:
    build:
      context: ./Server
    image: server
    container_name: server
    command: ["npm", "run", "start:dev"]
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - SERVER_HOST:${SERVER_HOST}
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_SCHEMA}
    ports:
    - "${PORT}:${PORT}"
    volumes:
      - ./Server/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro     
      - dbdata:/var/lib/mysql
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules: 